AllCops:
  Include:
    - 'lib/**/*.rb'
    - 'spec/**/*.rb'
  Exclude:
    - 'spec/dummy/**/*'

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'

Lint/ConstantDefinitionInBlock:
  Enabled: false

Lint/MissingSuper:
  Exclude:
    - 'spec/**/*'
