source "https://rubygems.org"

gem "rails", "~> 8.1.3"
gem "puma", ">= 5.0"
gem "sqlite3"

# Load servus from parent directory
gem "servus", path: "../.."

# Windows does not include zoneinfo files
gem "tzinfo-data", platforms: %i[windows jruby]

group :development, :test do
  gem "debug", platforms: %i[mri windows], require: "debug/prelude"
end